export interface Product {
  name: string;
  imageUrl: any | null;
  nutrients: string[];
}

export const Products: Product[] = [
  { name: 'Acerola cherry', imageUrl: require('@/assets/images/products/acerola-cherry.webp'), nutrients: ['vitamin-c'] },
  { name: 'Almonds', imageUrl: require('@/assets/images/products/almonds.webp'), nutrients: ['iron', 'vitamin-b6', 'vitamin-b9', 'vitamin-b2', 'magnesium', 'potassium', 'vitamin-e', 'choline', 'methionine-cysteine', 'fiber'] },
  { name: 'Apple with skin', imageUrl: require('@/assets/images/products/apple-with-skin.webp'), nutrients: ['vitamin-c', 'fiber'] },
  { name: 'Avocado', imageUrl: require('@/assets/images/products/avocado.webp'), nutrients: ['vitamin-b6', 'vitamin-b9', 'vitamin-b2', 'magnesium', 'potassium', 'vitamin-e', 'omega-3', 'choline', 'methionine-cysteine', 'fiber'] },
  { name: 'Baked salmon', imageUrl: require('@/assets/images/products/baked-salmon.webp'), nutrients: ['vitamin-b6', 'vitamin-b12', 'magnesium', 'potassium', 'choline', 'methionine-cysteine'] },
  { name: 'Baked sweet potato', imageUrl: require('@/assets/images/products/baked-sweet-potato.webp'), nutrients: ['vitamin-b6', 'potassium'] },
  { name: 'Baked trout', imageUrl: require('@/assets/images/products/baked-trout.webp'), nutrients: ['vitamin-b12'] },
  { name: 'Banana', imageUrl: require('@/assets/images/products/banana.webp'), nutrients: ['vitamin-b6', 'vitamin-b9', 'magnesium', 'potassium', 'choline', 'vitamin-c'] },
  { name: 'Beef liver', imageUrl: require('@/assets/images/products/beef-liver.webp'), nutrients: ['iron'] },
  { name: 'Black currant', imageUrl: require('@/assets/images/products/black-currant.webp'), nutrients: ['vitamin-c'] },
  { name: 'Boiled chicken breast', imageUrl: require('@/assets/images/products/boiled-chicken-breast.webp'), nutrients: ['iron', 'vitamin-b6', 'vitamin-b12', 'choline', 'methionine-cysteine'] },
  { name: 'Boiled egg', imageUrl: require('@/assets/images/products/chicken-egg.webp'), nutrients: ['iron', 'vitamin-b1', 'vitamin-b6', 'vitamin-b9', 'vitamin-b12', 'vitamin-b2', 'vitamin-e', 'omega-3', 'choline', 'methionine-cysteine'] },
  { name: 'Boiled potato', imageUrl: require('@/assets/images/products/boiled-potato.webp'), nutrients: ['vitamin-b1', 'vitamin-b6', 'vitamin-b9', 'potassium', 'choline', 'vitamin-c'] },
  { name: 'Brie cheese', imageUrl: require('@/assets/images/products/brie-cheese.webp'), nutrients: ['vitamin-b12'] },
  { name: 'Canned sardines', imageUrl: require('@/assets/images/products/canned-sardines.webp'), nutrients: ['iron', 'vitamin-b12', 'omega-3'] },
  { name: 'Canned tuna', imageUrl: require('@/assets/images/products/canned-tuna.webp'), nutrients: ['vitamin-b6', 'vitamin-b12', 'potassium', 'choline', 'methionine-cysteine'] },
  { name: 'Canola oil', imageUrl: require('@/assets/images/products/canola-oil.webp'), nutrients: ['vitamin-e', 'omega-3'] },
  { name: 'Cashews', imageUrl: require('@/assets/images/products/cashews.webp'), nutrients: ['iron', 'vitamin-b6', 'magnesium', 'potassium'] },
  { name: 'Cheddar cheese', imageUrl: require('@/assets/images/products/cheddar-cheese.webp'), nutrients: ['vitamin-b12', 'vitamin-b2'] },
  { name: 'Chia seeds', imageUrl: require('@/assets/images/products/chia-seeds.webp'), nutrients: ['fiber'] },
  { name: 'Chicken egg', imageUrl: require('@/assets/images/products/chicken-egg.webp'), nutrients: ['iron', 'magnesium'] },
  { name: 'Chicken liver', imageUrl: require('@/assets/images/products/chicken-liver.webp'), nutrients: ['iron'] },
  { name: 'Cooked Atlantic salmon', imageUrl: require('@/assets/images/products/cooked-atlantic-salmon.webp'), nutrients: ['omega-3'] },
  { name: 'Cooked beef liver', imageUrl: require('@/assets/images/products/beef-liver.webp'), nutrients: ['iron', 'vitamin-b1', 'vitamin-b6', 'vitamin-b9', 'vitamin-b12', 'vitamin-b2', 'choline', 'methionine-cysteine'] },
  { name: 'Cooked Brussels sprouts', imageUrl: require('@/assets/images/products/cooked-brussels-sprouts.webp'), nutrients: ['vitamin-b9'] },
  { name: 'Cooked asparagus', imageUrl: require('@/assets/images/products/cooked-asparagus.webp'), nutrients: ['vitamin-b9'] },
  { name: 'Cooked bluefin tuna', imageUrl: require('@/assets/images/products/cooked-bluefin-tuna.webp'), nutrients: ['omega-3'] },
  { name: 'Cooked broccoli', imageUrl: require('@/assets/images/products/cooked-broccoli.webp'), nutrients: ['iron', 'vitamin-b9', 'magnesium', 'potassium', 'vitamin-e', 'choline', 'methionine-cysteine', 'vitamin-c', 'fiber'] },
  { name: 'Cooked brown rice', imageUrl: require('@/assets/images/products/cooked-brown-rice.webp'), nutrients: ['vitamin-b6', 'vitamin-b9', 'magnesium', 'potassium', 'choline', 'methionine-cysteine'] },
  { name: 'Cooked buckwheat', imageUrl: require('@/assets/images/products/cooked-buckwheat.webp'), nutrients: ['iron', 'vitamin-b1', 'vitamin-b6', 'magnesium', 'potassium', 'methionine-cysteine'] },
  { name: 'Cooked chickpeas', imageUrl: require('@/assets/images/products/cooked-chickpeas.webp'), nutrients: ['iron', 'vitamin-b1', 'vitamin-b6', 'vitamin-b9', 'magnesium', 'potassium', 'choline', 'methionine-cysteine'] },
  { name: 'Cooked green peas', imageUrl: require('@/assets/images/products/cooked-green-peas.webp'), nutrients: ['iron', 'vitamin-b1', 'vitamin-b6', 'vitamin-b9'] },
  { name: 'Cooked kidney beans', imageUrl: require('@/assets/images/products/cooked-kidney-beans.webp'), nutrients: ['iron', 'vitamin-b6', 'potassium'] },
  { name: 'Cooked lentils', imageUrl: require('@/assets/images/products/cooked-lentils.webp'), nutrients: ['iron', 'vitamin-b1', 'vitamin-b6', 'vitamin-b9', 'vitamin-b2', 'magnesium', 'potassium', 'choline', 'methionine-cysteine', 'fiber'] },
  { name: 'Cooked millet', imageUrl: require('@/assets/images/products/cooked-millet.webp'), nutrients: ['iron', 'vitamin-b6', 'vitamin-b9', 'magnesium', 'potassium'] },
  { name: 'Cooked mushrooms', imageUrl: require('@/assets/images/products/cooked-mushrooms.webp'), nutrients: ['vitamin-b2'] },
  { name: 'Cooked mussels', imageUrl: require('@/assets/images/products/cooked-mussels.webp'), nutrients: ['vitamin-b12'] },
  { name: 'Cooked oats', imageUrl: require('@/assets/images/products/cooked-oats.webp'), nutrients: ['iron', 'vitamin-b1', 'vitamin-b6', 'vitamin-b9', 'vitamin-b2', 'magnesium', 'potassium', 'choline', 'methionine-cysteine', 'fiber'] },
  { name: 'Cooked pearl barley', imageUrl: require('@/assets/images/products/cooked-pearl-barley.webp'), nutrients: ['iron'] },
  { name: 'Cooked pork', imageUrl: require('@/assets/images/products/cooked-pork.webp'), nutrients: ['vitamin-b1'] },
  { name: 'Cooked spinach', imageUrl: require('@/assets/images/products/cooked-spinach.webp'), nutrients: ['iron', 'vitamin-b6', 'vitamin-b9', 'vitamin-b2', 'magnesium', 'potassium', 'vitamin-e', 'omega-3', 'methionine-cysteine'] },
  { name: 'Cooked white beans', imageUrl: require('@/assets/images/products/cooked-white-beans.webp'), nutrients: ['iron', 'vitamin-b1', 'vitamin-b6', 'vitamin-b9', 'magnesium', 'potassium', 'choline', 'methionine-cysteine'] },
  { name: 'Cooked beans', imageUrl: require('@/assets/images/products/cooked-white-beans.webp'), nutrients: ['vitamin-b2', 'fiber'] },
  { name: 'Cottage cheese', imageUrl: require('@/assets/images/products/cottage-cheese.webp'), nutrients: ['vitamin-b12', 'choline', 'methionine-cysteine'] },
  { name: 'Dark chocolate (70%)', imageUrl: require('@/assets/images/products/dark-chocolate-70.webp'), nutrients: ['iron', 'magnesium'] },
  { name: 'Dates', imageUrl: require('@/assets/images/products/dates.webp'), nutrients: ['iron', 'vitamin-b6', 'vitamin-b9', 'magnesium', 'potassium'] },
  { name: 'Dried apricots', imageUrl: require('@/assets/images/products/dried-apricots.webp'), nutrients: ['iron', 'vitamin-b6', 'vitamin-b9', 'magnesium', 'potassium'] },
  { name: 'Dried figs', imageUrl: require('@/assets/images/products/dried-figs.webp'), nutrients: ['iron', 'vitamin-b6', 'vitamin-b9', 'magnesium', 'potassium', 'fiber'] },
  { name: 'Dry oats', imageUrl: require('@/assets/images/products/dry-oats.webp'), nutrients: ['fiber'] },
  { name: 'Durum wheat pasta', imageUrl: require('@/assets/images/products/durum-wheat-pasta.webp'), nutrients: ['magnesium', 'potassium'] },
  { name: 'Flaxseed oil', imageUrl: require('@/assets/images/products/flaxseed-oil.webp'), nutrients: ['omega-3'] },
  { name: 'Flaxseed', imageUrl: require('@/assets/images/products/flaxseed.webp'), nutrients: ['fiber'] },
  { name: 'Fortified cereal', imageUrl: require('@/assets/images/products/fortified-cereal.webp'), nutrients: ['vitamin-e', 'choline'] },
  { name: 'Fortified nutritional yeast', imageUrl: require('@/assets/images/products/fortified-nutritional-yeast.webp'), nutrients: ['vitamin-b12'] },
  { name: 'Fortified plant milk', imageUrl: require('@/assets/images/products/fortified-plant-milk.webp'), nutrients: ['choline'] },
  { name: 'Fresh parsley', imageUrl: require('@/assets/images/products/fresh-parsley.webp'), nutrients: ['vitamin-c'] },
  { name: 'Fresh strawberries', imageUrl: require('@/assets/images/products/fresh-strawberries.webp'), nutrients: ['magnesium', 'potassium', 'vitamin-c'] },
  { name: 'Grapefruit', imageUrl: require('@/assets/images/products/grapefruit.webp'), nutrients: ['vitamin-c'] },
  { name: 'Ground flaxseed', imageUrl: require('@/assets/images/products/ground-flaxseed.webp'), nutrients: ['omega-3'] },
  { name: 'Hazelnuts', imageUrl: require('@/assets/images/products/hazelnuts.webp'), nutrients: ['vitamin-e', 'methionine-cysteine'] },
  { name: 'Kiwifruit', imageUrl: require('@/assets/images/products/kiwifruit.webp'), nutrients: ['vitamin-e', 'vitamin-c'] },
  { name: 'Orange', imageUrl: require('@/assets/images/products/orange.webp'), nutrients: ['vitamin-b9', 'magnesium', 'potassium', 'choline', 'vitamin-c'] },
  { name: 'Orange juice', imageUrl: require('@/assets/images/products/orange.webp'), nutrients: ['vitamin-b9', 'potassium'] },
  { name: 'Pacific herring, cooked', imageUrl: require('@/assets/images/products/pacific-herring-cooked.webp'), nutrients: ['omega-3'] },
  { name: 'Peanuts', imageUrl: require('@/assets/images/products/peanuts.webp'), nutrients: ['vitamin-b1', 'magnesium', 'vitamin-e'] },
  { name: 'Pear with skin', imageUrl: require('@/assets/images/products/pear-with-skin.webp'), nutrients: ['fiber'] },
  { name: 'Pistachios', imageUrl: require('@/assets/images/products/pistachios.webp'), nutrients: ['vitamin-b6', 'vitamin-b9', 'magnesium', 'vitamin-e', 'fiber'] },
  { name: 'Plain yogurt', imageUrl: require('@/assets/images/products/plain-yogurt.webp'), nutrients: ['vitamin-b6', 'vitamin-b9', 'vitamin-b12', 'vitamin-b2', 'magnesium', 'potassium', 'vitamin-e', 'omega-3', 'choline', 'methionine-cysteine'] },
  { name: 'Prunes', imageUrl: require('@/assets/images/products/prunes.webp'), nutrients: ['fiber'] },
  { name: 'Pumpkin seeds', imageUrl: require('@/assets/images/products/pumpkin-seeds.webp'), nutrients: ['iron', 'vitamin-b6', 'vitamin-b9', 'magnesium', 'potassium', 'methionine-cysteine'] },
  { name: 'Raisins', imageUrl: require('@/assets/images/products/raisins.webp'), nutrients: ['iron', 'potassium'] },
  { name: 'Raspberries', imageUrl: require('@/assets/images/products/raspberries.webp'), nutrients: ['fiber'] },
  { name: 'Raw Atlantic mackerel', imageUrl: require('@/assets/images/products/raw-atlantic-mackerel.webp'), nutrients: ['omega-3'] },
  { name: 'Raw cabbage', imageUrl: require('@/assets/images/products/raw-cabbage.webp'), nutrients: ['vitamin-c'] },
  { name: 'Raw carrot', imageUrl: require('@/assets/images/products/raw-carrot.webp'), nutrients: ['fiber'] },
  { name: 'Raw spinach', imageUrl: require('@/assets/images/products/raw-spinach.webp'), nutrients: ['vitamin-c'] },
  { name: 'Red bell pepper, raw', imageUrl: require('@/assets/images/products/red-bell-pepper-raw.webp'), nutrients: ['vitamin-c'] },
  { name: 'Roast turkey', imageUrl: require('@/assets/images/products/roast-turkey.webp'), nutrients: ['iron', 'vitamin-b6', 'vitamin-b12', 'choline', 'methionine-cysteine'] },
  { name: 'Rose hips, raw', imageUrl: require('@/assets/images/products/rose-hips-raw.webp'), nutrients: ['vitamin-c'] },
  { name: 'Salmon fish oil', imageUrl: require('@/assets/images/products/salmon-fish-oil.webp'), nutrients: ['omega-3'] },
  { name: 'Sesame seeds', imageUrl: require('@/assets/images/products/sesame-seeds.webp'), nutrients: ['iron', 'magnesium'] },
  { name: 'Soybean oil', imageUrl: require('@/assets/images/products/soybean-oil.webp'), nutrients: ['vitamin-e', 'omega-3'] },
  { name: 'Stewed beef', imageUrl: require('@/assets/images/products/stewed-beef.webp'), nutrients: ['iron', 'vitamin-b6', 'vitamin-b12', 'choline', 'methionine-cysteine'] },
  { name: 'Sunflower seeds', imageUrl: require('@/assets/images/products/sunflower-seeds.webp'), nutrients: ['iron', 'vitamin-b1', 'vitamin-b6', 'vitamin-b9', 'magnesium', 'potassium', 'vitamin-e', 'choline', 'methionine-cysteine'] },
  { name: 'Tangerine', imageUrl: require('@/assets/images/products/tangerine.webp'), nutrients: ['vitamin-c'] },
  { name: 'Tofu', imageUrl: require('@/assets/images/products/tofu.webp'), nutrients: ['iron', 'magnesium'] },
  { name: 'Tomato juice', imageUrl: require('@/assets/images/products/tomato-juice.webp'), nutrients: ['potassium'] },
  { name: 'Tomato', imageUrl: require('@/assets/images/products/tomato.webp'), nutrients: ['vitamin-c'] },
  { name: 'Walnuts', imageUrl: require('@/assets/images/products/walnuts.webp'), nutrients: ['omega-3', 'choline'] },
  { name: 'White cabbage', imageUrl: require('@/assets/images/products/white-cabbage.webp'), nutrients: ['fiber'] },
  { name: 'Whole grain bread', imageUrl: require('@/assets/images/products/whole-grain-bread.webp'), nutrients: ['iron', 'vitamin-b1', 'vitamin-b6', 'vitamin-b9', 'magnesium', 'fiber'] },
  { name: 'Wheat bread', imageUrl: require('@/assets/images/products/whole-grain-bread.webp'), nutrients: ['vitamin-b2'] },
  { name: 'Whole milk', imageUrl: require('@/assets/images/products/whole-milk.webp'), nutrients: ['vitamin-b6', 'vitamin-b9', 'vitamin-b12', 'vitamin-b2', 'magnesium', 'potassium', 'vitamin-e', 'omega-3', 'choline', 'methionine-cysteine', 'vitamin-c'] },
  { name: 'Wheat germ oil', imageUrl: null, nutrients: ['vitamin-e'] },
  { name: 'Sunflower oil', imageUrl: null, nutrients: ['vitamin-e'] },
  { name: 'Corn oil', imageUrl: null, nutrients: ['vitamin-e'] },
  { name: 'Mango', imageUrl: null, nutrients: ['vitamin-e'] },
  { name: 'Cooked cauliflower', imageUrl: null, nutrients: ['choline', 'vitamin-c', 'fiber'] },
];
