import { STORAGE_URL } from '@/config/supabase'
export type NutrientAmount = { per100g: number; inPortion: number };

export type Omega3Amount = NutrientAmount & { type: 'ALA' | 'EPA+DHA' | 'DHA' };

export const NUTRIENTS = [
  'iron',
  'magnesium',
  'potassium',
  'vitamin-b1',
  'vitamin-b2',
  'vitamin-b6',
  'vitamin-b9',
  'vitamin-b12',
  'vitamin-c',
  'vitamin-e',
  'omega-3',
  'choline',
  'fiber',
  'methionine-cysteine',
  'antioxidants',
] as const;

export type Nutrient = (typeof NUTRIENTS)[number];

export const COMPOSITION_NUTRIENTS = [
  'iron',
  'magnesium',
  'potassium',
  'vitamin-b1',
  'vitamin-b2',
  'vitamin-b6',
  'vitamin-b9',
  'vitamin-b12',
  'vitamin-e',
  'omega-3',
  'choline',
  'methionine-cysteine',
  'vitamin-c',
  'fiber',
] as const;

export type CompositionNutrientKey = (typeof COMPOSITION_NUTRIENTS)[number];

export const C = {
  iron: 'iron',
  magnesium: 'magnesium',
  potassium: 'potassium',
  vitaminB1: 'vitamin-b1',
  vitaminB2: 'vitamin-b2',
  vitaminB6: 'vitamin-b6',
  vitaminB9: 'vitamin-b9',
  vitaminB12: 'vitamin-b12',
  vitaminE: 'vitamin-e',
  omega3: 'omega-3',
  choline: 'choline',
  methionineCysteine: 'methionine-cysteine',
  vitaminC: 'vitamin-c',
  fiber: 'fiber',
} as const;

export type ProductComposition = {
  portion: string;
  'omega-3'?: Omega3Amount;
} & Partial<Record<Exclude<CompositionNutrientKey, 'omega-3'>, NutrientAmount>>;

export type DietaryTag = 'vegan' | 'vegetarian';

export interface Product {
  name: string;
  imageUrl: string | null;
  nutrients: Nutrient[];
  composition?: ProductComposition;
  dietary?: DietaryTag;
}

export const Products: Product[] = [
  {
    name: 'Acerola cherry',
    imageUrl: `${STORAGE_URL}/products/acerola-cherry.webp`,
    dietary: 'vegan',
    nutrients: ['vitamin-c'],
    composition: {
      portion: '20g',
      [C.vitaminC]: { per100g: 1677, inPortion: 335.4 },
    },
  },
  {
    name: 'Almonds',
    imageUrl: `${STORAGE_URL}/products/almonds.webp`,
    dietary: 'vegan',
    nutrients: ['iron', 'vitamin-b6', 'vitamin-b9', 'vitamin-b2', 'magnesium', 'potassium', 'vitamin-e', 'choline', 'methionine-cysteine', 'fiber'],
    composition: {
      portion: '30g',
      [C.iron]: { per100g: 3.7, inPortion: 1.1 },
      [C.magnesium]: { per100g: 270, inPortion: 81 },
      [C.potassium]: { per100g: 705, inPortion: 212 },
      [C.vitaminB2]: { per100g: 1.1, inPortion: 0.33 },
      [C.vitaminB6]: { per100g: 0.14, inPortion: 0.04 },
      [C.vitaminB9]: { per100g: 50, inPortion: 15 },
      [C.vitaminE]: { per100g: 26.2, inPortion: 7.86 },
      [C.choline]: { per100g: 52, inPortion: 16 },
      [C.methionineCysteine]: { per100g: 210, inPortion: 63 },
      [C.fiber]: { per100g: 12.5, inPortion: 3.75 },
    },
  },
  {
    name: 'Apple with skin',
    imageUrl: `${STORAGE_URL}/products/apple-with-skin.webp`,
    dietary: 'vegan',
    nutrients: ['vitamin-c', 'fiber'],
    composition: {
      portion: '180g',
      [C.vitaminC]: { per100g: 5, inPortion: 9 },
      [C.fiber]: { per100g: 2.4, inPortion: 4.32 },
    },
  },
  {
    name: 'Avocado',
    imageUrl: `${STORAGE_URL}/products/avocado.webp`,
    dietary: 'vegan',
    nutrients: ['vitamin-b6', 'vitamin-b9', 'vitamin-b2', 'magnesium', 'potassium', 'vitamin-e', 'omega-3', 'choline', 'methionine-cysteine', 'fiber'],
    composition: {
      portion: '150g',
      [C.magnesium]: { per100g: 29, inPortion: 44 },
      [C.potassium]: { per100g: 485, inPortion: 728 },
      [C.vitaminB2]: { per100g: 0.13, inPortion: 0.2 },
      [C.vitaminB6]: { per100g: 0.29, inPortion: 0.44 },
      [C.vitaminB9]: { per100g: 81, inPortion: 122 },
      [C.vitaminE]: { per100g: 2.1, inPortion: 3.15 },
      [C.omega3]: { per100g: 0.11, inPortion: 0.17, type: 'ALA' },
      [C.choline]: { per100g: 14, inPortion: 21 },
      [C.methionineCysteine]: { per100g: 50, inPortion: 75 },
      [C.fiber]: { per100g: 6.7, inPortion: 10.05 },
    },
  },
  {
    name: 'Baked salmon',
    imageUrl: `${STORAGE_URL}/products/baked-salmon.webp`,
    nutrients: ['vitamin-b6', 'vitamin-b12', 'magnesium', 'potassium', 'choline', 'methionine-cysteine'],
    composition: {
      portion: '150g',
      [C.magnesium]: { per100g: 30, inPortion: 45 },
      [C.potassium]: { per100g: 384, inPortion: 576 },
      [C.vitaminB6]: { per100g: 0.64, inPortion: 0.96 },
      [C.vitaminB12]: { per100g: 2.8, inPortion: 4.2 },
      [C.choline]: { per100g: 56, inPortion: 84 },
      [C.methionineCysteine]: { per100g: 850, inPortion: 1275 },
    },
  },
  {
    name: 'Baked sweet potato',
    imageUrl: `${STORAGE_URL}/products/baked-sweet-potato.webp`,
    dietary: 'vegan',
    nutrients: ['vitamin-b6', 'potassium'],
    composition: {
      portion: '150g',
      [C.potassium]: { per100g: 337, inPortion: 506 },
      [C.vitaminB6]: { per100g: 0.21, inPortion: 0.32 },
    },
  },
  {
    name: 'Baked trout',
    imageUrl: `${STORAGE_URL}/products/baked-trout.webp`,
    nutrients: ['vitamin-b12'],
    composition: {
      portion: '150g',
      [C.vitaminB12]: { per100g: 7.5, inPortion: 11.3 },
    },
  },
  {
    name: 'Banana',
    imageUrl: `${STORAGE_URL}/products/banana.webp`,
    dietary: 'vegan',
    nutrients: ['vitamin-b6', 'vitamin-b9', 'magnesium', 'potassium', 'choline', 'vitamin-c'],
    composition: {
      portion: '120g',
      [C.magnesium]: { per100g: 27, inPortion: 32 },
      [C.potassium]: { per100g: 358, inPortion: 430 },
      [C.vitaminB6]: { per100g: 0.37, inPortion: 0.44 },
      [C.vitaminB9]: { per100g: 20, inPortion: 24 },
      [C.choline]: { per100g: 9, inPortion: 11 },
      [C.vitaminC]: { per100g: 9, inPortion: 10.8 },
    },
  },
  {
    name: 'Beef liver',
    imageUrl: `${STORAGE_URL}/products/beef-liver.webp`,
    nutrients: ['iron'],
    composition: { portion: '80g', iron: { per100g: 6.2, inPortion: 5.0 } },
  },
  {
    name: 'Black currant',
    imageUrl: `${STORAGE_URL}/products/black-currant.webp`,
    dietary: 'vegan',
    nutrients: ['vitamin-c'],
    composition: {
      portion: '50g',
      [C.vitaminC]: { per100g: 181, inPortion: 90.5 },
    },
  },
  {
    name: 'Boiled chicken breast',
    imageUrl: `${STORAGE_URL}/products/boiled-chicken-breast.webp`,
    nutrients: ['iron', 'vitamin-b6', 'vitamin-b12', 'choline', 'methionine-cysteine'],
    composition: {
      portion: '150g',
      [C.iron]: { per100g: 1.3, inPortion: 2.0 },
      [C.vitaminB6]: { per100g: 0.64, inPortion: 0.96 },
      [C.vitaminB12]: { per100g: 0.3, inPortion: 0.45 },
      [C.choline]: { per100g: 72, inPortion: 108 },
      [C.methionineCysteine]: { per100g: 880, inPortion: 1320 },
    },
  },
  {
    name: 'Boiled egg',
    imageUrl: `${STORAGE_URL}/products/chicken-egg.webp`,
    dietary: 'vegetarian',
    nutrients: ['iron', 'vitamin-b1', 'vitamin-b6', 'vitamin-b9', 'vitamin-b12', 'vitamin-b2', 'vitamin-e', 'omega-3', 'choline', 'methionine-cysteine'],
    composition: {
      portion: '100g',
      [C.iron]: { per100g: 1.2, inPortion: 1.2 },
      [C.magnesium]: { per100g: 10, inPortion: 10 },
      [C.vitaminB1]: { per100g: 0.02, inPortion: 0.02 },
      [C.vitaminB2]: { per100g: 0.51, inPortion: 0.51 },
      [C.vitaminB6]: { per100g: 0.12, inPortion: 0.12 },
      [C.vitaminB9]: { per100g: 22, inPortion: 22 },
      [C.vitaminB12]: { per100g: 0.6, inPortion: 0.6 },
      [C.vitaminE]: { per100g: 0.5, inPortion: 0.5 },
      [C.omega3]: { per100g: 0.037, inPortion: 0.037, type: 'DHA' },
      [C.choline]: { per100g: 294, inPortion: 294 },
      [C.methionineCysteine]: { per100g: 600, inPortion: 600 },
    },
  },
  {
    name: 'Boiled potato',
    imageUrl: `${STORAGE_URL}/products/boiled-potato.webp`,
    dietary: 'vegan',
    nutrients: ['vitamin-b1', 'vitamin-b6', 'vitamin-b9', 'potassium', 'choline', 'vitamin-c'],
    composition: {
      portion: '200g',
      [C.potassium]: { per100g: 379, inPortion: 758 },
      [C.vitaminB1]: { per100g: 0.08, inPortion: 0.16 },
      [C.vitaminB6]: { per100g: 0.3, inPortion: 0.6 },
      [C.vitaminB9]: { per100g: 15, inPortion: 30 },
      [C.choline]: { per100g: 16, inPortion: 32 },
      [C.vitaminC]: { per100g: 20, inPortion: 40 },
    },
  },
  {
    name: 'Brie cheese',
    imageUrl: `${STORAGE_URL}/products/brie-cheese.webp`,
    dietary: 'vegetarian',
    nutrients: ['vitamin-b12'],
    composition: {
      portion: '30g',
      [C.vitaminB12]: { per100g: 1.5, inPortion: 0.45 },
    },
  },
  {
    name: 'Canned sardines',
    imageUrl: `${STORAGE_URL}/products/canned-sardines.webp`,
    nutrients: ['iron', 'vitamin-b12', 'omega-3'],
    composition: {
      portion: '90g',
      [C.iron]: { per100g: 2.9, inPortion: 2.6 },
      [C.vitaminB12]: { per100g: 8.9, inPortion: 8.0 },
      [C.omega3]: { per100g: 1.463, inPortion: 1.32, type: 'EPA+DHA' },
    },
  },
  {
    name: 'Canned tuna',
    imageUrl: `${STORAGE_URL}/products/canned-tuna.webp`,
    nutrients: ['vitamin-b6', 'vitamin-b12', 'potassium', 'choline', 'methionine-cysteine'],
    composition: {
      portion: '100g',
      [C.potassium]: { per100g: 252, inPortion: 252 },
      [C.vitaminB6]: { per100g: 0.86, inPortion: 0.86 },
      [C.vitaminB12]: { per100g: 2.5, inPortion: 2.5 },
      [C.choline]: { per100g: 77, inPortion: 77 },
      [C.methionineCysteine]: { per100g: 820, inPortion: 820 },
    },
  },
  {
    name: 'Canola oil',
    imageUrl: `${STORAGE_URL}/products/canola-oil.webp`,
    dietary: 'vegan',
    nutrients: ['vitamin-e', 'omega-3'],
    composition: {
      portion: '10ml',
      [C.vitaminE]: { per100g: 15.3, inPortion: 1.53 },
      [C.omega3]: { per100g: 9.3, inPortion: 0.84, type: 'ALA' },
    },
  },
  {
    name: 'Cashews',
    imageUrl: `${STORAGE_URL}/products/cashews.webp`,
    dietary: 'vegan',
    nutrients: ['iron', 'vitamin-b6', 'magnesium', 'potassium'],
    composition: {
      portion: '30g',
      [C.iron]: { per100g: 6.0, inPortion: 1.8 },
      [C.magnesium]: { per100g: 292, inPortion: 88 },
      [C.potassium]: { per100g: 660, inPortion: 198 },
      [C.vitaminB6]: { per100g: 0.42, inPortion: 0.13 },
    },
  },
  {
    name: 'Cheddar cheese',
    imageUrl: `${STORAGE_URL}/products/cheddar-cheese.webp`,
    dietary: 'vegetarian',
    nutrients: ['vitamin-b12', 'vitamin-b2'],
    composition: {
      portion: '30g',
      [C.vitaminB2]: { per100g: 0.42, inPortion: 0.13 },
      [C.vitaminB12]: { per100g: 1.0, inPortion: 0.3 },
    },
  },
  {
    name: 'Chia seeds',
    imageUrl: `${STORAGE_URL}/products/chia-seeds.webp`,
    dietary: 'vegan',
    nutrients: ['fiber'],
    composition: {
      portion: '15g',
      [C.fiber]: { per100g: 34.4, inPortion: 5.16 },
    },
  },
  {
    name: 'Chicken egg',
    imageUrl: `${STORAGE_URL}/products/chicken-egg.webp`,
    dietary: 'vegetarian',
    nutrients: ['iron', 'magnesium'],
    composition: {
      portion: '100g',
      [C.iron]: { per100g: 1.2, inPortion: 1.2 },
      [C.magnesium]: { per100g: 10, inPortion: 10 },
    },
  },
  {
    name: 'Chicken liver',
    imageUrl: `${STORAGE_URL}/products/chicken-liver.webp`,
    nutrients: ['iron'],
    composition: { portion: '70g', iron: { per100g: 9.0, inPortion: 6.3 } },
  },
  {
    name: 'Cooked Atlantic salmon',
    imageUrl: `${STORAGE_URL}/products/cooked-atlantic-salmon.webp`,
    nutrients: ['omega-3'],
    composition: {
      portion: '100g',
      [C.omega3]: { per100g: 1.928, inPortion: 1.93, type: 'EPA+DHA' },
    },
  },
  {
    name: 'Cooked beef liver',
    imageUrl: `${STORAGE_URL}/products/beef-liver.webp`,
    nutrients: ['iron', 'vitamin-b1', 'vitamin-b6', 'vitamin-b9', 'vitamin-b12', 'vitamin-b2', 'choline', 'methionine-cysteine'],
    composition: {
      portion: '80g',
      [C.iron]: { per100g: 6.2, inPortion: 5.0 },
      [C.vitaminB1]: { per100g: 0.26, inPortion: 0.21 },
      [C.vitaminB2]: { per100g: 3.42, inPortion: 2.74 },
      [C.vitaminB6]: { per100g: 0.9, inPortion: 0.72 },
      [C.vitaminB9]: { per100g: 215, inPortion: 172 },
      [C.vitaminB12]: { per100g: 70.7, inPortion: 56.6 },
      [C.choline]: { per100g: 418, inPortion: 334 },
      [C.methionineCysteine]: { per100g: 910, inPortion: 728 },
    },
  },
  {
    name: 'Cooked Brussels sprouts',
    imageUrl: `${STORAGE_URL}/products/cooked-brussels-sprouts.webp`,
    dietary: 'vegan',
    nutrients: ['vitamin-b9'],
    composition: {
      portion: '150g',
      [C.vitaminB9]: { per100g: 60, inPortion: 90 },
    },
  },
  {
    name: 'Cooked asparagus',
    imageUrl: `${STORAGE_URL}/products/cooked-asparagus.webp`,
    dietary: 'vegan',
    nutrients: ['vitamin-b9'],
    composition: {
      portion: '120g',
      [C.vitaminB9]: { per100g: 149, inPortion: 179 },
    },
  },
  {
    name: 'Cooked bluefin tuna',
    imageUrl: `${STORAGE_URL}/products/cooked-bluefin-tuna.webp`,
    nutrients: ['omega-3'],
    composition: {
      portion: '85g',
      [C.omega3]: { per100g: 1.279, inPortion: 1.09, type: 'EPA+DHA' },
    },
  },
  {
    name: 'Cooked broccoli',
    imageUrl: `${STORAGE_URL}/products/cooked-broccoli.webp`,
    dietary: 'vegan',
    nutrients: ['iron', 'vitamin-b9', 'magnesium', 'potassium', 'vitamin-e', 'choline', 'methionine-cysteine', 'vitamin-c', 'fiber'],
    composition: {
      portion: '100g',
      [C.iron]: { per100g: 1.0, inPortion: 1.0 },
      [C.magnesium]: { per100g: 21, inPortion: 21 },
      [C.potassium]: { per100g: 316, inPortion: 316 },
      [C.vitaminB9]: { per100g: 108, inPortion: 108 },
      [C.vitaminE]: { per100g: 1.5, inPortion: 1.5 },
      [C.choline]: { per100g: 40, inPortion: 40 },
      [C.methionineCysteine]: { per100g: 90, inPortion: 90 },
      [C.vitaminC]: { per100g: 65, inPortion: 65 },
      [C.fiber]: { per100g: 3.3, inPortion: 3.3 },
    },
  },
  {
    name: 'Cooked brown rice',
    imageUrl: `${STORAGE_URL}/products/cooked-brown-rice.webp`,
    dietary: 'vegan',
    nutrients: ['vitamin-b6', 'vitamin-b9', 'magnesium', 'potassium', 'choline', 'methionine-cysteine'],
    composition: {
      portion: '200g',
      [C.magnesium]: { per100g: 44, inPortion: 88 },
      [C.potassium]: { per100g: 86, inPortion: 172 },
      [C.vitaminB6]: { per100g: 0.14, inPortion: 0.28 },
      [C.vitaminB9]: { per100g: 9, inPortion: 18 },
      [C.choline]: { per100g: 9, inPortion: 18 },
      [C.methionineCysteine]: { per100g: 160, inPortion: 320 },
    },
  },
  {
    name: 'Cooked buckwheat',
    imageUrl: `${STORAGE_URL}/products/cooked-buckwheat.webp`,
    dietary: 'vegan',
    nutrients: ['iron', 'vitamin-b1', 'vitamin-b6', 'magnesium', 'potassium', 'methionine-cysteine'],
    composition: {
      portion: '200g',
      [C.iron]: { per100g: 1.3, inPortion: 2.6 },
      [C.magnesium]: { per100g: 51, inPortion: 102 },
      [C.potassium]: { per100g: 88, inPortion: 176 },
      [C.vitaminB1]: { per100g: 0.18, inPortion: 0.36 },
      [C.vitaminB6]: { per100g: 0.21, inPortion: 0.42 },
      [C.methionineCysteine]: { per100g: 230, inPortion: 460 },
    },
  },
  {
    name: 'Cooked chickpeas',
    imageUrl: `${STORAGE_URL}/products/cooked-chickpeas.webp`,
    dietary: 'vegan',
    nutrients: ['iron', 'vitamin-b1', 'vitamin-b6', 'vitamin-b9', 'magnesium', 'potassium', 'choline', 'methionine-cysteine'],
    composition: {
      portion: '150g',
      [C.iron]: { per100g: 2.9, inPortion: 4.4 },
      [C.magnesium]: { per100g: 48, inPortion: 72 },
      [C.potassium]: { per100g: 291, inPortion: 437 },
      [C.vitaminB1]: { per100g: 0.12, inPortion: 0.18 },
      [C.vitaminB9]: { per100g: 172, inPortion: 258 },
      [C.choline]: { per100g: 43, inPortion: 65 },
      [C.methionineCysteine]: { per100g: 350, inPortion: 525 },
    },
  },
  {
    name: 'Cooked green peas',
    imageUrl: `${STORAGE_URL}/products/cooked-green-peas.webp`,
    dietary: 'vegan',
    nutrients: ['iron', 'vitamin-b1', 'vitamin-b6', 'vitamin-b9'],
    composition: {
      portion: '150g',
      [C.iron]: { per100g: 1.5, inPortion: 2.3 },
      [C.vitaminB1]: { per100g: 0.28, inPortion: 0.42 },
      [C.vitaminB6]: { per100g: 0.22, inPortion: 0.33 },
      [C.vitaminB9]: { per100g: 65, inPortion: 98 },
    },
  },
  {
    name: 'Cooked kidney beans',
    imageUrl: `${STORAGE_URL}/products/cooked-kidney-beans.webp`,
    dietary: 'vegan',
    nutrients: ['iron', 'vitamin-b6', 'potassium'],
    composition: {
      portion: '150g',
      [C.iron]: { per100g: 2.6, inPortion: 3.9 },
      [C.potassium]: { per100g: 405, inPortion: 608 },
      [C.vitaminB6]: { per100g: 0.21, inPortion: 0.32 },
    },
  },
  {
    name: 'Cooked lentils',
    imageUrl: `${STORAGE_URL}/products/cooked-lentils.webp`,
    dietary: 'vegan',
    nutrients: ['iron', 'vitamin-b1', 'vitamin-b6', 'vitamin-b9', 'vitamin-b2', 'magnesium', 'potassium', 'choline', 'methionine-cysteine', 'fiber'],
    composition: {
      portion: '150g',
      [C.iron]: { per100g: 3.3, inPortion: 5.0 },
      [C.magnesium]: { per100g: 36, inPortion: 54 },
      [C.potassium]: { per100g: 369, inPortion: 554 },
      [C.vitaminB1]: { per100g: 0.17, inPortion: 0.26 },
      [C.vitaminB2]: { per100g: 0.1, inPortion: 0.15 },
      [C.vitaminB6]: { per100g: 0.18, inPortion: 0.27 },
      [C.vitaminB9]: { per100g: 181, inPortion: 272 },
      [C.choline]: { per100g: 26, inPortion: 39 },
      [C.methionineCysteine]: { per100g: 390, inPortion: 585 },
      [C.fiber]: { per100g: 7.9, inPortion: 11.85 },
    },
  },
  {
    name: 'Cooked millet',
    imageUrl: `${STORAGE_URL}/products/cooked-millet.webp`,
    dietary: 'vegan',
    nutrients: ['iron', 'vitamin-b6', 'vitamin-b9', 'magnesium', 'potassium'],
    composition: {
      portion: '200g',
      [C.iron]: { per100g: 1.0, inPortion: 2.0 },
      [C.magnesium]: { per100g: 44, inPortion: 88 },
      [C.potassium]: { per100g: 62, inPortion: 124 },
      [C.vitaminB6]: { per100g: 0.19, inPortion: 0.38 },
      [C.vitaminB9]: { per100g: 8, inPortion: 16 },
    },
  },
  {
    name: 'Cooked mushrooms',
    imageUrl: `${STORAGE_URL}/products/cooked-mushrooms.webp`,
    dietary: 'vegan',
    nutrients: ['vitamin-b2'],
    composition: {
      portion: '100g',
      [C.vitaminB2]: { per100g: 0.49, inPortion: 0.49 },
    },
  },
  {
    name: 'Cooked mussels',
    imageUrl: `${STORAGE_URL}/products/cooked-mussels.webp`,
    nutrients: ['vitamin-b12'],
    composition: {
      portion: '100g',
      [C.vitaminB12]: { per100g: 20.4, inPortion: 20.4 },
    },
  },
  {
    name: 'Cooked oats',
    imageUrl: `${STORAGE_URL}/products/cooked-oats.webp`,
    dietary: 'vegan',
    nutrients: ['iron', 'vitamin-b1', 'vitamin-b6', 'vitamin-b9', 'vitamin-b2', 'magnesium', 'potassium', 'choline', 'methionine-cysteine', 'fiber'],
    composition: {
      portion: '200g',
      [C.iron]: { per100g: 1.5, inPortion: 3.0 },
      [C.magnesium]: { per100g: 27, inPortion: 54 },
      [C.potassium]: { per100g: 61, inPortion: 122 },
      [C.vitaminB1]: { per100g: 0.1, inPortion: 0.2 },
      [C.vitaminB2]: { per100g: 0.1, inPortion: 0.2 },
      [C.vitaminB6]: { per100g: 0.12, inPortion: 0.24 },
      [C.vitaminB9]: { per100g: 20, inPortion: 40 },
      [C.choline]: { per100g: 17, inPortion: 34 },
      [C.methionineCysteine]: { per100g: 210, inPortion: 420 },
      [C.fiber]: { per100g: 2.5, inPortion: 5 },
    },
  },
  {
    name: 'Cooked pearl barley',
    imageUrl: `${STORAGE_URL}/products/cooked-pearl-barley.webp`,
    dietary: 'vegan',
    nutrients: ['iron'],
    composition: { portion: '200g', iron: { per100g: 1.2, inPortion: 2.4 } },
  },
  {
    name: 'Cooked pork',
    imageUrl: `${STORAGE_URL}/products/cooked-pork.webp`,
    nutrients: ['vitamin-b1'],
    composition: { portion: '100g', 'vitamin-b1': { per100g: 0.85, inPortion: 0.85 } },
  },
  {
    name: 'Cooked spinach',
    imageUrl: `${STORAGE_URL}/products/cooked-spinach.webp`,
    dietary: 'vegan',
    nutrients: ['iron', 'vitamin-b6', 'vitamin-b9', 'vitamin-b2', 'magnesium', 'potassium', 'vitamin-e', 'omega-3', 'methionine-cysteine'],
    composition: {
      portion: '100g',
      [C.iron]: { per100g: 3.6, inPortion: 3.6 },
      [C.magnesium]: { per100g: 87, inPortion: 87 },
      [C.potassium]: { per100g: 466, inPortion: 466 },
      [C.vitaminB2]: { per100g: 0.24, inPortion: 0.24 },
      [C.vitaminB6]: { per100g: 0.24, inPortion: 0.24 },
      [C.vitaminB9]: { per100g: 146, inPortion: 146 },
      [C.vitaminE]: { per100g: 2.1, inPortion: 2.1 },
      [C.omega3]: { per100g: 0.11, inPortion: 0.11, type: 'ALA' },
      [C.methionineCysteine]: { per100g: 80, inPortion: 80 },
    },
  },
  {
    name: 'Cooked white beans',
    imageUrl: `${STORAGE_URL}/products/cooked-white-beans.webp`,
    dietary: 'vegan',
    nutrients: ['iron', 'vitamin-b1', 'vitamin-b6', 'vitamin-b9', 'magnesium', 'potassium', 'choline', 'methionine-cysteine'],
    composition: {
      portion: '150g',
      [C.iron]: { per100g: 2.9, inPortion: 4.4 },
      [C.magnesium]: { per100g: 50, inPortion: 75 },
      [C.potassium]: { per100g: 351, inPortion: 527 },
      [C.vitaminB1]: { per100g: 0.17, inPortion: 0.26 },
      [C.vitaminB6]: { per100g: 0.2, inPortion: 0.3 },
      [C.vitaminB9]: { per100g: 127, inPortion: 191 },
      [C.choline]: { per100g: 28, inPortion: 42 },
      [C.methionineCysteine]: { per100g: 330, inPortion: 495 },
    },
  },
  {
    name: 'Cooked beans',
    imageUrl: `${STORAGE_URL}/products/cooked-white-beans.webp`,
    dietary: 'vegan',
    nutrients: ['vitamin-b2', 'fiber'],
    composition: {
      portion: '150g',
      [C.vitaminB2]: { per100g: 0.13, inPortion: 0.2 },
      [C.fiber]: { per100g: 6.4, inPortion: 9.6 },
    },
  },
  {
    name: 'Cottage cheese',
    imageUrl: `${STORAGE_URL}/products/cottage-cheese.webp`,
    dietary: 'vegetarian',
    nutrients: ['vitamin-b12', 'choline', 'methionine-cysteine'],
    composition: {
      portion: '100g',
      [C.vitaminB12]: { per100g: 0.9, inPortion: 0.9 },
      [C.choline]: { per100g: 36, inPortion: 36 },
      [C.methionineCysteine]: { per100g: 340, inPortion: 340 },
    },
  },
  {
    name: 'Dark chocolate (70%)',
    imageUrl: `${STORAGE_URL}/products/dark-chocolate-70.webp`,
    dietary: 'vegan',
    nutrients: ['iron', 'magnesium'],
    composition: {
      portion: '30g',
      [C.iron]: { per100g: 3.4, inPortion: 1.0 },
      [C.magnesium]: { per100g: 228, inPortion: 68 },
    },
  },
  {
    name: 'Dates',
    imageUrl: `${STORAGE_URL}/products/dates.webp`,
    dietary: 'vegan',
    nutrients: ['iron', 'vitamin-b6', 'vitamin-b9', 'magnesium', 'potassium'],
    composition: {
      portion: '60g',
      [C.iron]: { per100g: 1.0, inPortion: 0.6 },
      [C.magnesium]: { per100g: 43, inPortion: 26 },
      [C.potassium]: { per100g: 656, inPortion: 394 },
      [C.vitaminB6]: { per100g: 0.24, inPortion: 0.14 },
      [C.vitaminB9]: { per100g: 15, inPortion: 9 },
    },
  },
  {
    name: 'Dried apricots',
    imageUrl: `${STORAGE_URL}/products/dried-apricots.webp`,
    dietary: 'vegan',
    nutrients: ['iron', 'vitamin-b6', 'vitamin-b9', 'magnesium', 'potassium'],
    composition: {
      portion: '40g',
      [C.iron]: { per100g: 3.6, inPortion: 1.4 },
      [C.magnesium]: { per100g: 51, inPortion: 20 },
      [C.potassium]: { per100g: 1162, inPortion: 465 },
      [C.vitaminB6]: { per100g: 0.23, inPortion: 0.09 },
      [C.vitaminB9]: { per100g: 10, inPortion: 4 },
    },
  },
  {
    name: 'Dried figs',
    imageUrl: `${STORAGE_URL}/products/dried-figs.webp`,
    dietary: 'vegan',
    nutrients: ['iron', 'vitamin-b6', 'vitamin-b9', 'magnesium', 'potassium', 'fiber'],
    composition: {
      portion: '40g',
      [C.iron]: { per100g: 2.0, inPortion: 0.8 },
      [C.magnesium]: { per100g: 68, inPortion: 27 },
      [C.potassium]: { per100g: 680, inPortion: 272 },
      [C.vitaminB6]: { per100g: 0.11, inPortion: 0.04 },
      [C.vitaminB9]: { per100g: 9, inPortion: 4 },
      [C.fiber]: { per100g: 9.8, inPortion: 3.92 },
    },
  },
  {
    name: 'Dry oats',
    imageUrl: `${STORAGE_URL}/products/dry-oats.webp`,
    dietary: 'vegan',
    nutrients: ['fiber'],
    composition: {
      portion: '40g',
      [C.fiber]: { per100g: 10.6, inPortion: 4.24 },
    },
  },
  {
    name: 'Durum wheat pasta',
    imageUrl: `${STORAGE_URL}/products/durum-wheat-pasta.webp`,
    dietary: 'vegan',
    nutrients: ['magnesium', 'potassium'],
    composition: {
      portion: '200g',
      [C.magnesium]: { per100g: 53, inPortion: 106 },
      [C.potassium]: { per100g: 44, inPortion: 88 },
    },
  },
  {
    name: 'Flaxseed oil',
    imageUrl: `${STORAGE_URL}/products/flaxseed-oil.webp`,
    dietary: 'vegan',
    nutrients: ['omega-3'],
    composition: {
      portion: '13.6g',
      [C.omega3]: { per100g: 53.3, inPortion: 7.25, type: 'ALA' },
    },
  },
  {
    name: 'Flaxseed',
    imageUrl: `${STORAGE_URL}/products/flaxseed.webp`,
    dietary: 'vegan',
    nutrients: ['fiber'],
    composition: {
      portion: '15g',
      [C.fiber]: { per100g: 27.3, inPortion: 4.1 },
    },
  },
  {
    name: 'Fortified cereal',
    imageUrl: `${STORAGE_URL}/products/fortified-cereal.webp`,
    dietary: 'vegan',
    nutrients: ['vitamin-e', 'choline'],
    composition: {
      portion: '30g',
      [C.vitaminE]: { per100g: 20.0, inPortion: 6.0 },
      [C.choline]: { per100g: 110, inPortion: 33 },
    },
  },
  {
    name: 'Fortified nutritional yeast',
    imageUrl: `${STORAGE_URL}/products/fortified-nutritional-yeast.webp`,
    dietary: 'vegan',
    nutrients: ['vitamin-b12'],
    composition: {
      portion: '5g',
      [C.vitaminB12]: { per100g: 24.0, inPortion: 1.2 },
    },
  },
  {
    name: 'Fortified plant milk',
    imageUrl: `${STORAGE_URL}/products/fortified-plant-milk.webp`,
    dietary: 'vegan',
    nutrients: ['choline'],
    composition: {
      portion: '200ml',
      [C.choline]: { per100g: 60, inPortion: 60 },
    },
  },
  {
    name: 'Fresh parsley',
    imageUrl: `${STORAGE_URL}/products/fresh-parsley.webp`,
    dietary: 'vegan',
    nutrients: ['vitamin-c'],
    composition: {
      portion: '10g',
      [C.vitaminC]: { per100g: 133, inPortion: 13.3 },
    },
  },
  {
    name: 'Fresh strawberries',
    imageUrl: `${STORAGE_URL}/products/fresh-strawberries.webp`,
    dietary: 'vegan',
    nutrients: ['magnesium', 'potassium', 'vitamin-c'],
    composition: {
      portion: '150g',
      [C.magnesium]: { per100g: 13, inPortion: 20 },
      [C.potassium]: { per100g: 153, inPortion: 230 },
      [C.vitaminC]: { per100g: 59, inPortion: 88.5 },
    },
  },
  {
    name: 'Grapefruit',
    imageUrl: `${STORAGE_URL}/products/grapefruit.webp`,
    dietary: 'vegan',
    nutrients: ['vitamin-c'],
    composition: {
      portion: '150g',
      [C.vitaminC]: { per100g: 38, inPortion: 57 },
    },
  },
  {
    name: 'Ground flaxseed',
    imageUrl: `${STORAGE_URL}/products/ground-flaxseed.webp`,
    dietary: 'vegan',
    nutrients: ['omega-3'],
    composition: {
      portion: '7g',
      [C.omega3]: { per100g: 22.8, inPortion: 1.6, type: 'ALA' },
    },
  },
  {
    name: 'Hazelnuts',
    imageUrl: `${STORAGE_URL}/products/hazelnuts.webp`,
    dietary: 'vegan',
    nutrients: ['vitamin-e', 'methionine-cysteine'],
    composition: {
      portion: '30g',
      [C.vitaminE]: { per100g: 15.0, inPortion: 4.5 },
      [C.methionineCysteine]: { per100g: 190, inPortion: 57 },
    },
  },
  {
    name: 'Kiwifruit',
    imageUrl: `${STORAGE_URL}/products/kiwifruit.webp`,
    dietary: 'vegan',
    nutrients: ['vitamin-e', 'vitamin-c'],
    composition: {
      portion: '100g',
      [C.vitaminE]: { per100g: 1.5, inPortion: 1.5 },
      [C.vitaminC]: { per100g: 93, inPortion: 93 },
    },
  },
  {
    name: 'Orange',
    imageUrl: `${STORAGE_URL}/products/orange.webp`,
    dietary: 'vegan',
    nutrients: ['vitamin-b9', 'magnesium', 'potassium', 'choline', 'vitamin-c'],
    composition: {
      portion: '130g',
      [C.magnesium]: { per100g: 14, inPortion: 18 },
      [C.potassium]: { per100g: 200, inPortion: 260 },
      [C.vitaminB9]: { per100g: 30, inPortion: 39 },
      [C.choline]: { per100g: 8, inPortion: 10 },
      [C.vitaminC]: { per100g: 53, inPortion: 69 },
    },
  },
  {
    name: 'Orange juice',
    imageUrl: `${STORAGE_URL}/products/orange.webp`,
    dietary: 'vegan',
    nutrients: ['vitamin-b9', 'potassium'],
    composition: {
      portion: '240ml',
      [C.potassium]: { per100g: 200, inPortion: 480 },
      [C.vitaminB9]: { per100g: 35, inPortion: 84 },
    },
  },
  {
    name: 'Pacific herring, cooked',
    imageUrl: `${STORAGE_URL}/products/pacific-herring-cooked.webp`,
    nutrients: ['omega-3'],
    composition: {
      portion: '144g',
      [C.omega3]: { per100g: 3.06, inPortion: 4.41, type: 'EPA+DHA' },
    },
  },
  {
    name: 'Peanuts',
    imageUrl: `${STORAGE_URL}/products/peanuts.webp`,
    dietary: 'vegan',
    nutrients: ['vitamin-b1', 'magnesium', 'vitamin-e'],
    composition: {
      portion: '30g',
      [C.magnesium]: { per100g: 168, inPortion: 50 },
      [C.vitaminB1]: { per100g: 0.44, inPortion: 0.13 },
      [C.vitaminE]: { per100g: 8.3, inPortion: 2.49 },
    },
  },
  {
    name: 'Pear with skin',
    imageUrl: `${STORAGE_URL}/products/pear-with-skin.webp`,
    dietary: 'vegan',
    nutrients: ['fiber'],
    composition: {
      portion: '180g',
      [C.fiber]: { per100g: 3.1, inPortion: 5.58 },
    },
  },
  {
    name: 'Pistachios',
    imageUrl: `${STORAGE_URL}/products/pistachios.webp`,
    dietary: 'vegan',
    nutrients: ['vitamin-b6', 'vitamin-b9', 'magnesium', 'vitamin-e', 'fiber'],
    composition: {
      portion: '30g',
      [C.magnesium]: { per100g: 121, inPortion: 36 },
      [C.vitaminB6]: { per100g: 1.12, inPortion: 0.34 },
      [C.vitaminB9]: { per100g: 51, inPortion: 15 },
      [C.vitaminE]: { per100g: 2.3, inPortion: 0.69 },
      [C.fiber]: { per100g: 10.3, inPortion: 3.09 },
    },
  },
  {
    name: 'Plain yogurt',
    imageUrl: `${STORAGE_URL}/products/plain-yogurt.webp`,
    dietary: 'vegetarian',
    nutrients: ['vitamin-b6', 'vitamin-b9', 'vitamin-b12', 'vitamin-b2', 'magnesium', 'potassium', 'vitamin-e', 'omega-3', 'choline', 'methionine-cysteine'],
    composition: {
      portion: '150g',
      [C.magnesium]: { per100g: 19, inPortion: 29 },
      [C.potassium]: { per100g: 234, inPortion: 351 },
      [C.vitaminB2]: { per100g: 0.27, inPortion: 0.41 },
      [C.vitaminB6]: { per100g: 0.08, inPortion: 0.12 },
      [C.vitaminB9]: { per100g: 7, inPortion: 11 },
      [C.vitaminB12]: { per100g: 0.5, inPortion: 0.75 },
      [C.vitaminE]: { per100g: 0.1, inPortion: 0.15 },
      [C.omega3]: { per100g: 0.003, inPortion: 0.005, type: 'DHA' },
      [C.choline]: { per100g: 43, inPortion: 65 },
      [C.methionineCysteine]: { per100g: 160, inPortion: 240 },
    },
  },
  {
    name: 'Prunes',
    imageUrl: `${STORAGE_URL}/products/prunes.webp`,
    dietary: 'vegan',
    nutrients: ['fiber'],
    composition: {
      portion: '50g',
      [C.fiber]: { per100g: 7.1, inPortion: 3.55 },
    },
  },
  {
    name: 'Pumpkin seeds',
    imageUrl: `${STORAGE_URL}/products/pumpkin-seeds.webp`,
    dietary: 'vegan',
    nutrients: ['iron', 'vitamin-b6', 'vitamin-b9', 'magnesium', 'potassium', 'methionine-cysteine'],
    composition: {
      portion: '20g',
      [C.iron]: { per100g: 8.8, inPortion: 1.8 },
      [C.magnesium]: { per100g: 535, inPortion: 107 },
      [C.potassium]: { per100g: 588, inPortion: 118 },
      [C.vitaminB6]: { per100g: 0.14, inPortion: 0.03 },
      [C.vitaminB9]: { per100g: 58, inPortion: 12 },
      [C.methionineCysteine]: { per100g: 390, inPortion: 78 },
    },
  },
  {
    name: 'Raisins',
    imageUrl: `${STORAGE_URL}/products/raisins.webp`,
    dietary: 'vegan',
    nutrients: ['iron', 'potassium'],
    composition: {
      portion: '40g',
      [C.iron]: { per100g: 1.9, inPortion: 0.8 },
      [C.potassium]: { per100g: 749, inPortion: 300 },
    },
  },
  {
    name: 'Raspberries',
    imageUrl: `${STORAGE_URL}/products/raspberries.webp`,
    dietary: 'vegan',
    nutrients: ['fiber'],
    composition: {
      portion: '100g',
      [C.fiber]: { per100g: 6.5, inPortion: 6.5 },
    },
  },
  {
    name: 'Raw Atlantic mackerel',
    imageUrl: `${STORAGE_URL}/products/raw-atlantic-mackerel.webp`,
    nutrients: ['omega-3'],
    composition: {
      portion: '112g',
      [C.omega3]: { per100g: 2.575, inPortion: 2.88, type: 'EPA+DHA' },
    },
  },
  {
    name: 'Raw cabbage',
    imageUrl: `${STORAGE_URL}/products/raw-cabbage.webp`,
    dietary: 'vegan',
    nutrients: ['vitamin-c'],
    composition: {
      portion: '100g',
      [C.vitaminC]: { per100g: 36, inPortion: 36 },
    },
  },
  {
    name: 'Raw carrot',
    imageUrl: `${STORAGE_URL}/products/raw-carrot.webp`,
    dietary: 'vegan',
    nutrients: ['fiber'],
    composition: {
      portion: '100g',
      [C.fiber]: { per100g: 2.8, inPortion: 2.8 },
    },
  },
  {
    name: 'Raw spinach',
    imageUrl: `${STORAGE_URL}/products/raw-spinach.webp`,
    dietary: 'vegan',
    nutrients: ['vitamin-c'],
    composition: {
      portion: '50g',
      [C.vitaminC]: { per100g: 28, inPortion: 14 },
    },
  },
  {
    name: 'Red bell pepper, raw',
    imageUrl: `${STORAGE_URL}/products/red-bell-pepper-raw.webp`,
    dietary: 'vegan',
    nutrients: ['vitamin-c'],
    composition: {
      portion: '100g',
      [C.vitaminC]: { per100g: 127, inPortion: 127 },
    },
  },
  {
    name: 'Roast turkey',
    imageUrl: `${STORAGE_URL}/products/roast-turkey.webp`,
    nutrients: ['iron', 'vitamin-b6', 'vitamin-b12', 'choline', 'methionine-cysteine'],
    composition: {
      portion: '150g',
      [C.iron]: { per100g: 1.6, inPortion: 2.4 },
      [C.vitaminB12]: { per100g: 1.1, inPortion: 1.65 },
      [C.choline]: { per100g: 85, inPortion: 128 },
      [C.methionineCysteine]: { per100g: 950, inPortion: 1425 },
    },
  },
  {
    name: 'Rose hips, raw',
    imageUrl: `${STORAGE_URL}/products/rose-hips-raw.webp`,
    dietary: 'vegan',
    nutrients: ['vitamin-c'],
    composition: {
      portion: '30g',
      [C.vitaminC]: { per100g: 426, inPortion: 127.8 },
    },
  },
  {
    name: 'Salmon fish oil',
    imageUrl: `${STORAGE_URL}/products/salmon-fish-oil.webp`,
    nutrients: ['omega-3'],
    composition: {
      portion: '13.6g',
      [C.omega3]: { per100g: 4.251, inPortion: 5.78, type: 'EPA+DHA' },
    },
  },
  {
    name: 'Sesame seeds',
    imageUrl: `${STORAGE_URL}/products/sesame-seeds.webp`,
    dietary: 'vegan',
    nutrients: ['iron', 'magnesium'],
    composition: {
      portion: '15g',
      [C.iron]: { per100g: 6.5, inPortion: 1.0 },
      [C.magnesium]: { per100g: 356, inPortion: 53 },
    },
  },
  {
    name: 'Soybean oil',
    imageUrl: `${STORAGE_URL}/products/soybean-oil.webp`,
    dietary: 'vegan',
    nutrients: ['vitamin-e', 'omega-3'],
    composition: {
      portion: '10ml',
      [C.vitaminE]: { per100g: 8.6, inPortion: 0.86 },
      [C.omega3]: { per100g: 6.8, inPortion: 0.61, type: 'ALA' },
    },
  },
  {
    name: 'Stewed beef',
    imageUrl: `${STORAGE_URL}/products/stewed-beef.webp`,
    nutrients: ['iron', 'vitamin-b6', 'vitamin-b12', 'choline', 'methionine-cysteine'],
    composition: {
      portion: '120g',
      [C.iron]: { per100g: 2.6, inPortion: 3.1 },
      [C.vitaminB6]: { per100g: 0.34, inPortion: 0.41 },
      [C.vitaminB12]: { per100g: 1.5, inPortion: 1.8 },
      [C.choline]: { per100g: 117, inPortion: 140 },
      [C.methionineCysteine]: { per100g: 910, inPortion: 1092 },
    },
  },
  {
    name: 'Sunflower seeds',
    imageUrl: `${STORAGE_URL}/products/sunflower-seeds.webp`,
    dietary: 'vegan',
    nutrients: ['iron', 'vitamin-b1', 'vitamin-b6', 'vitamin-b9', 'magnesium', 'potassium', 'vitamin-e', 'choline', 'methionine-cysteine'],
    composition: {
      portion: '20g',
      [C.iron]: { per100g: 5.0, inPortion: 1.0 },
      [C.magnesium]: { per100g: 359, inPortion: 72 },
      [C.potassium]: { per100g: 645, inPortion: 129 },
      [C.vitaminB1]: { per100g: 1.48, inPortion: 0.3 },
      [C.vitaminB6]: { per100g: 1.35, inPortion: 0.27 },
      [C.vitaminB9]: { per100g: 238, inPortion: 48 },
      [C.vitaminE]: { per100g: 49.1, inPortion: 9.82 },
      [C.choline]: { per100g: 55, inPortion: 11 },
      [C.methionineCysteine]: { per100g: 440, inPortion: 88 },
    },
  },
  {
    name: 'Tangerine',
    imageUrl: `${STORAGE_URL}/products/tangerine.webp`,
    dietary: 'vegan',
    nutrients: ['vitamin-c'],
    composition: {
      portion: '120g',
      [C.vitaminC]: { per100g: 27, inPortion: 32.4 },
    },
  },
  {
    name: 'Tofu',
    imageUrl: `${STORAGE_URL}/products/tofu.webp`,
    dietary: 'vegan',
    nutrients: ['iron', 'magnesium'],
    composition: {
      portion: '100g',
      [C.iron]: { per100g: 5.4, inPortion: 5.4 },
      [C.magnesium]: { per100g: 65, inPortion: 65 },
    },
  },
  {
    name: 'Tomato juice',
    imageUrl: `${STORAGE_URL}/products/tomato-juice.webp`,
    dietary: 'vegan',
    nutrients: ['potassium'],
    composition: { portion: '240ml', potassium: { per100g: 217, inPortion: 520 } },
  },
  {
    name: 'Tomato',
    imageUrl: `${STORAGE_URL}/products/tomato.webp`,
    dietary: 'vegan',
    nutrients: ['vitamin-c'],
    composition: {
      portion: '120g',
      [C.vitaminC]: { per100g: 14, inPortion: 16.8 },
    },
  },
  {
    name: 'Walnuts',
    imageUrl: `${STORAGE_URL}/products/walnuts.webp`,
    dietary: 'vegan',
    nutrients: ['omega-3', 'choline'],
    composition: {
      portion: '30g',
      [C.omega3]: { per100g: 9.1, inPortion: 2.73, type: 'ALA' },
      [C.choline]: { per100g: 39, inPortion: 12 },
    },
  },
  {
    name: 'White cabbage',
    imageUrl: `${STORAGE_URL}/products/white-cabbage.webp`,
    dietary: 'vegan',
    nutrients: ['fiber'],
    composition: {
      portion: '100g',
      [C.fiber]: { per100g: 2.5, inPortion: 2.5 },
    },
  },
  {
    name: 'Whole grain bread',
    imageUrl: `${STORAGE_URL}/products/whole-grain-bread.webp`,
    dietary: 'vegan',
    nutrients: ['iron', 'vitamin-b1', 'vitamin-b6', 'vitamin-b9', 'magnesium', 'fiber'],
    composition: {
      portion: '60g',
      [C.iron]: { per100g: 2.5, inPortion: 1.5 },
      [C.magnesium]: { per100g: 75, inPortion: 45 },
      [C.potassium]: { per100g: 75, inPortion: 45 },
      [C.vitaminB1]: { per100g: 0.43, inPortion: 0.26 },
      [C.vitaminB6]: { per100g: 0.27, inPortion: 0.16 },
      [C.vitaminB9]: { per100g: 30, inPortion: 18 },
      [C.fiber]: { per100g: 6.9, inPortion: 4.14 },
    },
  },
  {
    name: 'Wheat bread',
    imageUrl: `${STORAGE_URL}/products/whole-grain-bread.webp`,
    dietary: 'vegan',
    nutrients: ['vitamin-b2'],
    composition: {
      portion: '40g',
      [C.vitaminB2]: { per100g: 0.11, inPortion: 0.044 },
    },
  },
  {
    name: 'Whole milk',
    imageUrl: `${STORAGE_URL}/products/whole-milk.webp`,
    dietary: 'vegetarian',
    nutrients: ['vitamin-b6', 'vitamin-b9', 'vitamin-b12', 'vitamin-b2', 'magnesium', 'potassium', 'vitamin-e', 'omega-3', 'choline', 'methionine-cysteine', 'vitamin-c'],
    composition: {
      portion: '200ml',
      [C.magnesium]: { per100g: 11, inPortion: 22 },
      [C.potassium]: { per100g: 156, inPortion: 312 },
      [C.vitaminB2]: { per100g: 0.18, inPortion: 0.36 },
      [C.vitaminB6]: { per100g: 0.04, inPortion: 0.08 },
      [C.vitaminB9]: { per100g: 5, inPortion: 10 },
      [C.vitaminB12]: { per100g: 0.4, inPortion: 0.8 },
      [C.vitaminE]: { per100g: 0.1, inPortion: 0.2 },
      [C.omega3]: { per100g: 0.004, inPortion: 0.008, type: 'DHA' },
      [C.choline]: { per100g: 38, inPortion: 76 },
      [C.methionineCysteine]: { per100g: 120, inPortion: 240 },
      [C.vitaminC]: { per100g: 1, inPortion: 2 },
    },
  },
  {
    name: 'Wheat germ oil',
    imageUrl: `${STORAGE_URL}/products/wheat-germ-oil.webp`,
    dietary: 'vegan',
    nutrients: ['vitamin-e'],
    composition: {
      portion: '5ml',
      [C.vitaminE]: { per100g: 149.4, inPortion: 7.47 },
    },
  },
  {
    name: 'Sunflower oil',
    imageUrl: `${STORAGE_URL}/products/sunflower-oil.webp`,
    dietary: 'vegan',
    nutrients: ['vitamin-e'],
    composition: {
      portion: '10ml',
      [C.vitaminE]: { per100g: 41.1, inPortion: 4.11 },
    },
  },
  {
    name: 'Corn oil',
    imageUrl: `${STORAGE_URL}/products/corn-oil.webp`,
    dietary: 'vegan',
    nutrients: ['vitamin-e'],
    composition: {
      portion: '10ml',
      [C.vitaminE]: { per100g: 14.3, inPortion: 1.43 },
    },
  },
  {
    name: 'Mango',
    imageUrl: `${STORAGE_URL}/products/mango.webp`,
    dietary: 'vegan',
    nutrients: ['vitamin-e'],
    composition: {
      portion: '200g',
      [C.vitaminE]: { per100g: 0.9, inPortion: 1.8 },
    },
  },
  {
    name: 'Cooked cauliflower',
    imageUrl: `${STORAGE_URL}/products/cooked-cauliflower.webp`,
    dietary: 'vegan',
    nutrients: ['choline', 'vitamin-c', 'fiber'],
    composition: {
      portion: '150g',
      [C.choline]: { per100g: 39, inPortion: 59 },
      [C.vitaminC]: { per100g: 48, inPortion: 72 },
      [C.fiber]: { per100g: 2.3, inPortion: 3.45 },
    },
  },
];

const normalizeName = (str: string) =>
  str.toLowerCase().trim().replace(/\s*\([^)]*\)\s*/g, '');

export function getProductQuantity(productName: string): string {
  const normalized = normalizeName(productName);
  const product = Products.find((p) => {
    const pNormalized = normalizeName(p.name);
    return pNormalized === normalized || p.name.toLowerCase().includes(normalized) || normalized.includes(p.name.toLowerCase());
  });
  return product?.composition?.portion ?? '100g';
}
