export const PRODUCTS_NAMES = {
  "Acerola cherry": "acerola-cherry",
  "Almonds": "almonds",
  "Apple with skin": "apple-with-skin",
  "Avocado": "avocado",
  "Baked salmon": "baked-salmon",
  "Baked sweet potato": "baked-sweet-potato",
  "Baked trout": "baked-trout",
  "Banana": "banana",
  "Beef liver": "beef-liver",
  "Black currant": "black-currant",
  "Boiled chicken breast": "boiled-chicken-breast",
  "Boiled potato": "boiled-potato",
  "Brie cheese": "brie-cheese",
  "Canned sardines": "canned-sardines",
  "Canned tuna": "canned-tuna",
  "Canola oil": "canola-oil",
  "Cashews": "cashews",
  "Cheddar cheese": "cheddar-cheese",
  "Chia seeds": "chia-seeds",
  "Chicken egg": "chicken-egg",
  "Chicken liver": "chicken-liver",
  "Cooked Atlantic salmon": "cooked-atlantic-salmon",
  "Cooked Brussels sprouts": "cooked-brussels-sprouts",
  "Cooked asparagus": "cooked-asparagus",
  "Cooked bluefin tuna": "cooked-bluefin-tuna",
  "Cooked broccoli": "cooked-broccoli",
  "Cooked brown rice": "cooked-brown-rice",
  "Cooked buckwheat": "cooked-buckwheat",
  "Cooked chickpeas": "cooked-chickpeas",
  "Cooked green peas": "cooked-green-peas",
  "Cooked kidney beans": "cooked-kidney-beans",
  "Cooked lentils": "cooked-lentils",
  "Cooked millet": "cooked-millet",
  "Cooked mushrooms": "cooked-mushrooms",
  "Cooked mussels": "cooked-mussels",
  "Cooked oats": "cooked-oats",
  "Cooked pearl barley": "cooked-pearl-barley",
  "Cooked pork": "cooked-pork",
  "Cooked spinach": "cooked-spinach",
  "Cooked white beans": "cooked-white-beans",
  "Cottage cheese": "cottage-cheese",
  "Dark chocolate (70%)": "dark-chocolate-(70%)",
  "Dates": "dates",
  "Dried apricots": "dried-apricots",
  "Dried figs": "dried-figs",
  "Dry oats": "dry-oats",
  "Durum wheat pasta": "durum-wheat-pasta",
  "Flaxseed oil": "flaxseed-oil",
  "Flaxseed": "flaxseed",
  "Fortified cereal": "fortified-cereal",
  "Fortified nutritional yeast": "fortified-nutritional-yeast",
  "Fortified plant milk": "fortified-plant-milk",
  "Fresh parsley": "fresh-parsley",
  "Fresh strawberries": "fresh-strawberries",
  "Grapefruit": "grapefruit",
  "Ground flaxseed": "ground-flaxseed",
  "Hazelnuts": "hazelnuts",
  "Kiwifruit": "kiwifruit",
  "Orange": "orange",
  "Pacific herring, cooked": "pacific-herring-cooked",
  "Peanuts": "peanuts",
  "Pear with skin": "pear-with-skin",
  "Pistachios": "pistachios",
  "Plain yogurt": "plain-yogurt",
  "Prunes": "prunes",
  "Pumpkin seeds": "pumpkin-seeds",
  "Raisins": "raisins",
  "Raspberries": "raspberries",
  "Raw Atlantic mackerel": "raw-atlantic-mackerel",
  "Raw cabbage": "raw-cabbage",
  "Raw carrot": "raw-carrot",
  "Raw spinach": "raw-spinach",
  "Red bell pepper, raw": "red-bell-pepper-raw",
  "Roast turkey": "roast-turkey",
  "Rose hips, raw": "rose-hips-raw",
  "Salmon fish oil": "salmon-fish-oil",
  "Sesame seeds": "sesame-seeds",
  "Soybean oil": "soybean-oil",
  "Stewed beef": "stewed-beef",
  "Sunflower seeds": "sunflower-seeds",
  "Tangerine": "tangerine",
  "Tofu": "tofu",
  "Tomato juice": "tomato-juice",
  "Tomato": "tomato",
  "Walnuts": "walnuts",
  "White cabbage": "white-cabbage",
  "Whole grain bread": "whole-grain-bread",
  "Whole milk": "whole-milk"
} as const;


export const PRODUCTS_IMAGES: Record<string, any> = {
  'Acerola cherry': require('../../assets/images/products/acerola-cherry.webp'),
  'Almonds': require('../../assets/images/products/almonds.webp'),
  'Apple with skin': require('../../assets/images/products/apple-with-skin.webp'),
  'Avocado': require('../../assets/images/products/avocado.webp'),
  'Baked salmon': require('../../assets/images/products/baked-salmon.webp'),
  'Baked sweet potato': require('../../assets/images/products/baked-sweet-potato.webp'),
  'Baked trout': require('../../assets/images/products/baked-trout.webp'),
  'Banana': require('../../assets/images/products/banana.webp'),
  'Beef liver': require('../../assets/images/products/beef-liver.webp'),
  'Black currant': require('../../assets/images/products/black-currant.webp'),
  'Boiled chicken breast': require('../../assets/images/products/boiled-chicken-breast.webp'),
  'Boiled potato': require('../../assets/images/products/boiled-potato.webp'),
  'Brie cheese': require('../../assets/images/products/brie-cheese.webp'),
  'Canned sardines': require('../../assets/images/products/canned-sardines.webp'),
  'Canned tuna': require('../../assets/images/products/canned-tuna.webp'),
  'Canola oil': require('../../assets/images/products/canola-oil.webp'),
  'Cashews': require('../../assets/images/products/cashews.webp'),
  'Cheddar cheese': require('../../assets/images/products/cheddar-cheese.webp'),
  'Chia seeds': require('../../assets/images/products/chia-seeds.webp'),
  'Chicken egg': require('../../assets/images/products/chicken-egg.webp'),
  'Chicken liver': require('../../assets/images/products/chicken-liver.webp'),
  'Cooked Atlantic salmon': require('../../assets/images/products/cooked-atlantic-salmon.webp'),
  'Cooked Brussels sprouts': require('../../assets/images/products/cooked-brussels-sprouts.webp'),
  'Cooked asparagus': require('../../assets/images/products/cooked-asparagus.webp'),
  'Cooked bluefin tuna': require('../../assets/images/products/cooked-bluefin-tuna.webp'),
  'Cooked broccoli': require('../../assets/images/products/cooked-broccoli.webp'),
  'Cooked brown rice': require('../../assets/images/products/cooked-brown-rice.webp'),
  'Cooked buckwheat': require('../../assets/images/products/cooked-buckwheat.webp'),
  'Cooked chickpeas': require('../../assets/images/products/cooked-chickpeas.webp'),
  'Cooked green peas': require('../../assets/images/products/cooked-green-peas.webp'),
  'Cooked kidney beans': require('../../assets/images/products/cooked-kidney-beans.webp'),
  'Cooked lentils': require('../../assets/images/products/cooked-lentils.webp'),
  'Cooked millet': require('../../assets/images/products/cooked-millet.webp'),
  'Cooked mushrooms': require('../../assets/images/products/cooked-mushrooms.webp'),
  'Cooked mussels': require('../../assets/images/products/cooked-mussels.webp'),
  'Cooked oats': require('../../assets/images/products/cooked-oats.webp'),
  'Cooked pearl barley': require('../../assets/images/products/cooked-pearl-barley.webp'),
  'Cooked pork': require('../../assets/images/products/cooked-pork.webp'),
  'Cooked spinach': require('../../assets/images/products/cooked-spinach.webp'),
  'Cooked white beans': require('../../assets/images/products/cooked-white-beans.webp'),
  'Cottage cheese': require('../../assets/images/products/cottage-cheese.webp'),
  'Dark chocolate (70%)': require('../../assets/images/products/dark-chocolate-(70%).webp'),
  'Dates': require('../../assets/images/products/dates.webp'),
  'Dried apricots': require('../../assets/images/products/dried-apricots.webp'),
  'Dried figs': require('../../assets/images/products/dried-figs.webp'),
  'Dry oats': require('../../assets/images/products/dry-oats.webp'),
  'Durum wheat pasta': require('../../assets/images/products/durum-wheat-pasta.webp'),
  'Flaxseed oil': require('../../assets/images/products/flaxseed-oil.webp'),
  'Flaxseed': require('../../assets/images/products/flaxseed.webp'),
  'Fortified cereal': require('../../assets/images/products/fortified-cereal.webp'),
  'Fortified nutritional yeast': require('../../assets/images/products/fortified-nutritional-yeast.webp'),
  'Fortified plant milk': require('../../assets/images/products/fortified-plant-milk.webp'),
  'Fresh parsley': require('../../assets/images/products/fresh-parsley.webp'),
  'Fresh strawberries': require('../../assets/images/products/fresh-strawberries.webp'),
  'Grapefruit': require('../../assets/images/products/grapefruit.webp'),
  'Ground flaxseed': require('../../assets/images/products/ground-flaxseed.webp'),
  'Hazelnuts': require('../../assets/images/products/hazelnuts.webp'),
  'Kiwifruit': require('../../assets/images/products/kiwifruit.webp'),
  'Orange': require('../../assets/images/products/orange.webp'),
  'Pacific herring, cooked': require('../../assets/images/products/pacific-herring-cooked.webp'),
  'Peanuts': require('../../assets/images/products/peanuts.webp'),
  'Pear with skin': require('../../assets/images/products/pear-with-skin.webp'),
  'Pistachios': require('../../assets/images/products/pistachios.webp'),
  'Plain yogurt': require('../../assets/images/products/plain-yogurt.webp'),
  'Prunes': require('../../assets/images/products/prunes.webp'),
  'Pumpkin seeds': require('../../assets/images/products/pumpkin-seeds.webp'),
  'Raisins': require('../../assets/images/products/raisins.webp'),
  'Raspberries': require('../../assets/images/products/raspberries.webp'),
  'Raw Atlantic mackerel': require('../../assets/images/products/raw-atlantic-mackerel.webp'),
  'Raw cabbage': require('../../assets/images/products/raw-cabbage.webp'),
  'Raw carrot': require('../../assets/images/products/raw-carrot.webp'),
  'Raw spinach': require('../../assets/images/products/raw-spinach.webp'),
  'Red bell pepper, raw': require('../../assets/images/products/red-bell-pepper-raw.webp'),
  'Roast turkey': require('../../assets/images/products/roast-turkey.webp'),
  'Rose hips, raw': require('../../assets/images/products/rose-hips-raw.webp'),
  'Salmon fish oil': require('../../assets/images/products/salmon-fish-oil.webp'),
  'Sesame seeds': require('../../assets/images/products/sesame-seeds.webp'),
  'Soybean oil': require('../../assets/images/products/soybean-oil.webp'),
  'Stewed beef': require('../../assets/images/products/stewed-beef.webp'),
  'Sunflower seeds': require('../../assets/images/products/sunflower-seeds.webp'),
  'Tangerine': require('../../assets/images/products/tangerine.webp'),
  'Tofu': require('../../assets/images/products/tofu.webp'),
  'Tomato juice': require('../../assets/images/products/tomato-juice.webp'),
  'Tomato': require('../../assets/images/products/tomato.webp'),
  'Walnuts': require('../../assets/images/products/walnuts.webp'),
  'White cabbage': require('../../assets/images/products/white-cabbage.webp'),
  'Whole grain bread': require('../../assets/images/products/whole-grain-bread.webp'),
  'Whole milk': require('../../assets/images/products/whole-milk.webp'),
}

export interface Product {
  name: string;
  imageUrl: any | null;
  nutrients: string[];
}

export const Products: Product[] = [
  { name: 'Acerola cherry', imageUrl: require('../../assets/images/products/acerola-cherry.webp'), nutrients: ['vitamin-c'] },
  { name: 'Almonds', imageUrl: require('../../assets/images/products/almonds.webp'), nutrients: ['iron', 'vitamin-b6', 'vitamin-b9', 'vitamin-b2', 'magnesium', 'potassium', 'vitamin-e', 'choline', 'methionine-cysteine', 'fiber'] },
  { name: 'Apple with skin', imageUrl: require('../../assets/images/products/apple-with-skin.webp'), nutrients: ['vitamin-c', 'fiber'] },
  { name: 'Avocado', imageUrl: require('../../assets/images/products/avocado.webp'), nutrients: ['vitamin-b6', 'vitamin-b9', 'vitamin-b2', 'magnesium', 'potassium', 'vitamin-e', 'omega-3', 'choline', 'methionine-cysteine', 'fiber'] },
  { name: 'Baked salmon', imageUrl: require('../../assets/images/products/baked-salmon.webp'), nutrients: ['vitamin-b6', 'vitamin-b12', 'magnesium', 'potassium', 'choline', 'methionine-cysteine'] },
  { name: 'Baked sweet potato', imageUrl: require('../../assets/images/products/baked-sweet-potato.webp'), nutrients: ['vitamin-b6', 'potassium'] },
  { name: 'Baked trout', imageUrl: require('../../assets/images/products/baked-trout.webp'), nutrients: ['vitamin-b12'] },
  { name: 'Banana', imageUrl: require('../../assets/images/products/banana.webp'), nutrients: ['vitamin-b6', 'vitamin-b9', 'magnesium', 'potassium', 'choline', 'vitamin-c'] },
  { name: 'Beef liver', imageUrl: require('../../assets/images/products/beef-liver.webp'), nutrients: ['iron'] },
  { name: 'Black currant', imageUrl: require('../../assets/images/products/black-currant.webp'), nutrients: ['vitamin-c'] },
  { name: 'Boiled chicken breast', imageUrl: require('../../assets/images/products/boiled-chicken-breast.webp'), nutrients: ['iron', 'vitamin-b6', 'vitamin-b12', 'choline', 'methionine-cysteine'] },
  { name: 'Boiled egg', imageUrl: require('../../assets/images/products/chicken-egg.webp'), nutrients: ['iron', 'vitamin-b1', 'vitamin-b6', 'vitamin-b9', 'vitamin-b12', 'vitamin-b2', 'vitamin-e', 'omega-3', 'choline', 'methionine-cysteine'] },
  { name: 'Boiled potato', imageUrl: require('../../assets/images/products/boiled-potato.webp'), nutrients: ['vitamin-b1', 'vitamin-b6', 'vitamin-b9', 'potassium', 'choline', 'vitamin-c'] },
  { name: 'Brie cheese', imageUrl: require('../../assets/images/products/brie-cheese.webp'), nutrients: ['vitamin-b12'] },
  { name: 'Canned sardines', imageUrl: require('../../assets/images/products/canned-sardines.webp'), nutrients: ['iron', 'vitamin-b12', 'omega-3'] },
  { name: 'Canned tuna', imageUrl: require('../../assets/images/products/canned-tuna.webp'), nutrients: ['vitamin-b6', 'vitamin-b12', 'potassium', 'choline', 'methionine-cysteine'] },
  { name: 'Canola oil', imageUrl: require('../../assets/images/products/canola-oil.webp'), nutrients: ['vitamin-e', 'omega-3'] },
  { name: 'Cashews', imageUrl: require('../../assets/images/products/cashews.webp'), nutrients: ['iron', 'vitamin-b6', 'magnesium', 'potassium'] },
  { name: 'Cheddar cheese', imageUrl: require('../../assets/images/products/cheddar-cheese.webp'), nutrients: ['vitamin-b12', 'vitamin-b2'] },
  { name: 'Chia seeds', imageUrl: require('../../assets/images/products/chia-seeds.webp'), nutrients: ['fiber'] },
  { name: 'Chicken egg', imageUrl: require('../../assets/images/products/chicken-egg.webp'), nutrients: ['iron', 'magnesium'] },
  { name: 'Chicken liver', imageUrl: require('../../assets/images/products/chicken-liver.webp'), nutrients: ['iron'] },
  { name: 'Cooked Atlantic salmon', imageUrl: require('../../assets/images/products/cooked-atlantic-salmon.webp'), nutrients: ['omega-3'] },
  { name: 'Cooked beef liver', imageUrl: require('../../assets/images/products/beef-liver.webp'), nutrients: ['iron', 'vitamin-b1', 'vitamin-b6', 'vitamin-b9', 'vitamin-b12', 'vitamin-b2', 'choline', 'methionine-cysteine'] },
  { name: 'Cooked Brussels sprouts', imageUrl: require('../../assets/images/products/cooked-brussels-sprouts.webp'), nutrients: ['vitamin-b9'] },
  { name: 'Cooked asparagus', imageUrl: require('../../assets/images/products/cooked-asparagus.webp'), nutrients: ['vitamin-b9'] },
  { name: 'Cooked bluefin tuna', imageUrl: require('../../assets/images/products/cooked-bluefin-tuna.webp'), nutrients: ['omega-3'] },
  { name: 'Cooked broccoli', imageUrl: require('../../assets/images/products/cooked-broccoli.webp'), nutrients: ['iron', 'vitamin-b9', 'magnesium', 'potassium', 'vitamin-e', 'choline', 'methionine-cysteine', 'vitamin-c', 'fiber'] },
  { name: 'Cooked brown rice', imageUrl: require('../../assets/images/products/cooked-brown-rice.webp'), nutrients: ['vitamin-b6', 'vitamin-b9', 'magnesium', 'potassium', 'choline', 'methionine-cysteine'] },
  { name: 'Cooked buckwheat', imageUrl: require('../../assets/images/products/cooked-buckwheat.webp'), nutrients: ['iron', 'vitamin-b1', 'vitamin-b6', 'magnesium', 'potassium', 'methionine-cysteine'] },
  { name: 'Cooked chickpeas', imageUrl: require('../../assets/images/products/cooked-chickpeas.webp'), nutrients: ['iron', 'vitamin-b1', 'vitamin-b6', 'vitamin-b9', 'magnesium', 'potassium', 'choline', 'methionine-cysteine'] },
  { name: 'Cooked green peas', imageUrl: require('../../assets/images/products/cooked-green-peas.webp'), nutrients: ['iron', 'vitamin-b1', 'vitamin-b6', 'vitamin-b9'] },
  { name: 'Cooked kidney beans', imageUrl: require('../../assets/images/products/cooked-kidney-beans.webp'), nutrients: ['iron', 'vitamin-b6', 'potassium'] },
  { name: 'Cooked lentils', imageUrl: require('../../assets/images/products/cooked-lentils.webp'), nutrients: ['iron', 'vitamin-b1', 'vitamin-b6', 'vitamin-b9', 'vitamin-b2', 'magnesium', 'potassium', 'choline', 'methionine-cysteine', 'fiber'] },
  { name: 'Cooked millet', imageUrl: require('../../assets/images/products/cooked-millet.webp'), nutrients: ['iron', 'vitamin-b6', 'vitamin-b9', 'magnesium', 'potassium'] },
  { name: 'Cooked mushrooms', imageUrl: require('../../assets/images/products/cooked-mushrooms.webp'), nutrients: ['vitamin-b2'] },
  { name: 'Cooked mussels', imageUrl: require('../../assets/images/products/cooked-mussels.webp'), nutrients: ['vitamin-b12'] },
  { name: 'Cooked oats', imageUrl: require('../../assets/images/products/cooked-oats.webp'), nutrients: ['iron', 'vitamin-b1', 'vitamin-b6', 'vitamin-b9', 'vitamin-b2', 'magnesium', 'potassium', 'choline', 'methionine-cysteine', 'fiber'] },
  { name: 'Cooked pearl barley', imageUrl: require('../../assets/images/products/cooked-pearl-barley.webp'), nutrients: ['iron'] },
  { name: 'Cooked pork', imageUrl: require('../../assets/images/products/cooked-pork.webp'), nutrients: ['vitamin-b1'] },
  { name: 'Cooked spinach', imageUrl: require('../../assets/images/products/cooked-spinach.webp'), nutrients: ['iron', 'vitamin-b6', 'vitamin-b9', 'vitamin-b2', 'magnesium', 'potassium', 'vitamin-e', 'omega-3', 'methionine-cysteine'] },
  { name: 'Cooked white beans', imageUrl: require('../../assets/images/products/cooked-white-beans.webp'), nutrients: ['iron', 'vitamin-b1', 'vitamin-b6', 'vitamin-b9', 'magnesium', 'potassium', 'choline', 'methionine-cysteine'] },
  { name: 'Cooked beans', imageUrl: require('../../assets/images/products/cooked-white-beans.webp'), nutrients: ['vitamin-b2', 'fiber'] },
  { name: 'Cottage cheese', imageUrl: require('../../assets/images/products/cottage-cheese.webp'), nutrients: ['vitamin-b12', 'choline', 'methionine-cysteine'] },
  { name: 'Dark chocolate (70%)', imageUrl: require('../../assets/images/products/dark-chocolate-(70%).webp'), nutrients: ['iron', 'magnesium'] },
  { name: 'Dates', imageUrl: require('../../assets/images/products/dates.webp'), nutrients: ['iron', 'vitamin-b6', 'vitamin-b9', 'magnesium', 'potassium'] },
  { name: 'Dried apricots', imageUrl: require('../../assets/images/products/dried-apricots.webp'), nutrients: ['iron', 'vitamin-b6', 'vitamin-b9', 'magnesium', 'potassium'] },
  { name: 'Dried figs', imageUrl: require('../../assets/images/products/dried-figs.webp'), nutrients: ['iron', 'vitamin-b6', 'vitamin-b9', 'magnesium', 'potassium', 'fiber'] },
  { name: 'Dry oats', imageUrl: require('../../assets/images/products/dry-oats.webp'), nutrients: ['fiber'] },
  { name: 'Durum wheat pasta', imageUrl: require('../../assets/images/products/durum-wheat-pasta.webp'), nutrients: ['magnesium', 'potassium'] },
  { name: 'Flaxseed oil', imageUrl: require('../../assets/images/products/flaxseed-oil.webp'), nutrients: ['omega-3'] },
  { name: 'Flaxseed', imageUrl: require('../../assets/images/products/flaxseed.webp'), nutrients: ['fiber'] },
  { name: 'Fortified cereal', imageUrl: require('../../assets/images/products/fortified-cereal.webp'), nutrients: ['vitamin-e', 'choline'] },
  { name: 'Fortified nutritional yeast', imageUrl: require('../../assets/images/products/fortified-nutritional-yeast.webp'), nutrients: ['vitamin-b12'] },
  { name: 'Fortified plant milk', imageUrl: require('../../assets/images/products/fortified-plant-milk.webp'), nutrients: ['choline'] },
  { name: 'Fresh parsley', imageUrl: require('../../assets/images/products/fresh-parsley.webp'), nutrients: ['vitamin-c'] },
  { name: 'Fresh strawberries', imageUrl: require('../../assets/images/products/fresh-strawberries.webp'), nutrients: ['magnesium', 'potassium', 'vitamin-c'] },
  { name: 'Grapefruit', imageUrl: require('../../assets/images/products/grapefruit.webp'), nutrients: ['vitamin-c'] },
  { name: 'Ground flaxseed', imageUrl: require('../../assets/images/products/ground-flaxseed.webp'), nutrients: ['omega-3'] },
  { name: 'Hazelnuts', imageUrl: require('../../assets/images/products/hazelnuts.webp'), nutrients: ['vitamin-e', 'methionine-cysteine'] },
  { name: 'Kiwifruit', imageUrl: require('../../assets/images/products/kiwifruit.webp'), nutrients: ['vitamin-e', 'vitamin-c'] },
  { name: 'Orange', imageUrl: require('../../assets/images/products/orange.webp'), nutrients: ['vitamin-b9', 'magnesium', 'potassium', 'choline', 'vitamin-c'] },
  { name: 'Orange juice', imageUrl: require('../../assets/images/products/orange.webp'), nutrients: ['vitamin-b9', 'potassium'] },
  { name: 'Pacific herring, cooked', imageUrl: require('../../assets/images/products/pacific-herring-cooked.webp'), nutrients: ['omega-3'] },
  { name: 'Peanuts', imageUrl: require('../../assets/images/products/peanuts.webp'), nutrients: ['vitamin-b1', 'magnesium', 'vitamin-e'] },
  { name: 'Pear with skin', imageUrl: require('../../assets/images/products/pear-with-skin.webp'), nutrients: ['fiber'] },
  { name: 'Pistachios', imageUrl: require('../../assets/images/products/pistachios.webp'), nutrients: ['vitamin-b6', 'vitamin-b9', 'magnesium', 'vitamin-e', 'fiber'] },
  { name: 'Plain yogurt', imageUrl: require('../../assets/images/products/plain-yogurt.webp'), nutrients: ['vitamin-b6', 'vitamin-b9', 'vitamin-b12', 'vitamin-b2', 'magnesium', 'potassium', 'vitamin-e', 'omega-3', 'choline', 'methionine-cysteine'] },
  { name: 'Prunes', imageUrl: require('../../assets/images/products/prunes.webp'), nutrients: ['fiber'] },
  { name: 'Pumpkin seeds', imageUrl: require('../../assets/images/products/pumpkin-seeds.webp'), nutrients: ['iron', 'vitamin-b6', 'vitamin-b9', 'magnesium', 'potassium', 'methionine-cysteine'] },
  { name: 'Raisins', imageUrl: require('../../assets/images/products/raisins.webp'), nutrients: ['iron', 'potassium'] },
  { name: 'Raspberries', imageUrl: require('../../assets/images/products/raspberries.webp'), nutrients: ['fiber'] },
  { name: 'Raw Atlantic mackerel', imageUrl: require('../../assets/images/products/raw-atlantic-mackerel.webp'), nutrients: ['omega-3'] },
  { name: 'Raw cabbage', imageUrl: require('../../assets/images/products/raw-cabbage.webp'), nutrients: ['vitamin-c'] },
  { name: 'Raw carrot', imageUrl: require('../../assets/images/products/raw-carrot.webp'), nutrients: ['fiber'] },
  { name: 'Raw spinach', imageUrl: require('../../assets/images/products/raw-spinach.webp'), nutrients: ['vitamin-c'] },
  { name: 'Red bell pepper, raw', imageUrl: require('../../assets/images/products/red-bell-pepper-raw.webp'), nutrients: ['vitamin-c'] },
  { name: 'Roast turkey', imageUrl: require('../../assets/images/products/roast-turkey.webp'), nutrients: ['iron', 'vitamin-b6', 'vitamin-b12', 'choline', 'methionine-cysteine'] },
  { name: 'Rose hips, raw', imageUrl: require('../../assets/images/products/rose-hips-raw.webp'), nutrients: ['vitamin-c'] },
  { name: 'Salmon fish oil', imageUrl: require('../../assets/images/products/salmon-fish-oil.webp'), nutrients: ['omega-3'] },
  { name: 'Sesame seeds', imageUrl: require('../../assets/images/products/sesame-seeds.webp'), nutrients: ['iron', 'magnesium'] },
  { name: 'Soybean oil', imageUrl: require('../../assets/images/products/soybean-oil.webp'), nutrients: ['vitamin-e', 'omega-3'] },
  { name: 'Stewed beef', imageUrl: require('../../assets/images/products/stewed-beef.webp'), nutrients: ['iron', 'vitamin-b6', 'vitamin-b12', 'choline', 'methionine-cysteine'] },
  { name: 'Sunflower seeds', imageUrl: require('../../assets/images/products/sunflower-seeds.webp'), nutrients: ['iron', 'vitamin-b1', 'vitamin-b6', 'vitamin-b9', 'magnesium', 'potassium', 'vitamin-e', 'choline', 'methionine-cysteine'] },
  { name: 'Tangerine', imageUrl: require('../../assets/images/products/tangerine.webp'), nutrients: ['vitamin-c'] },
  { name: 'Tofu', imageUrl: require('../../assets/images/products/tofu.webp'), nutrients: ['iron', 'magnesium'] },
  { name: 'Tomato juice', imageUrl: require('../../assets/images/products/tomato-juice.webp'), nutrients: ['potassium'] },
  { name: 'Tomato', imageUrl: require('../../assets/images/products/tomato.webp'), nutrients: ['vitamin-c'] },
  { name: 'Walnuts', imageUrl: require('../../assets/images/products/walnuts.webp'), nutrients: ['omega-3', 'choline'] },
  { name: 'White cabbage', imageUrl: require('../../assets/images/products/white-cabbage.webp'), nutrients: ['fiber'] },
  { name: 'Whole grain bread', imageUrl: require('../../assets/images/products/whole-grain-bread.webp'), nutrients: ['iron', 'vitamin-b1', 'vitamin-b6', 'vitamin-b9', 'magnesium', 'fiber'] },
  { name: 'Wheat bread', imageUrl: require('../../assets/images/products/whole-grain-bread.webp'), nutrients: ['vitamin-b2'] },
  { name: 'Whole milk', imageUrl: require('../../assets/images/products/whole-milk.webp'), nutrients: ['vitamin-b6', 'vitamin-b9', 'vitamin-b12', 'vitamin-b2', 'magnesium', 'potassium', 'vitamin-e', 'omega-3', 'choline', 'methionine-cysteine', 'vitamin-c'] },
  { name: 'Wheat germ oil', imageUrl: null, nutrients: ['vitamin-e'] },
  { name: 'Sunflower oil', imageUrl: null, nutrients: ['vitamin-e'] },
  { name: 'Corn oil', imageUrl: null, nutrients: ['vitamin-e'] },
  { name: 'Mango', imageUrl: null, nutrients: ['vitamin-e'] },
  { name: 'Cooked cauliflower', imageUrl: null, nutrients: ['choline', 'vitamin-c', 'fiber'] },
];

// Products that are missing from the list
export const MissingProducts: string[] = [
  'Wheat germ oil',
  'Sunflower oil',
  'Corn oil',
  'Mango',
  'Cooked cauliflower'
];

//94 items